# Generated by Django 6.0.4 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_payment_method',
            field=models.CharField(choices=[('card', 'Картой онлайн'), ('cash', 'Наличными при получении'), ('transfer', 'Переводом')], max_length=20),
        ),
    ]
