from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from apps.catalog.models import ProductCategory, Product, ProductImage
from apps.cart.models import Cart, CartItem
from apps.orders.models import Order, OrderItem


class Command(BaseCommand):
    help = "Заполняет базу данных тестовыми категориями, товарами, корзиной и заказом"

    def handle(self, *args, **kwargs):
        User = get_user_model()

        user, _ = User.objects.get_or_create(
            username="demo_user",
            defaults={
                "email": "demo_user@test.com",
                "first_name": "Demo",
                "last_name": "User",
            },
        )
        user.set_password("Demo12345!")
        user.save()

        categories = [
            ("Гостиная", "gostinaya"),
            ("Спальня", "spalnya"),
            ("Кухня", "kuhnya"),
            ("Прихожая", "prihozhaya"),
            ("Ванная", "vannaya"),
            ("Кабинет", "kabinet"),
            ("Детская", "detskaya"),
        ]

        category_objects = {}

        for name, slug in categories:
            category, _ = ProductCategory.objects.update_or_create(
                product_category_slug=slug,
                defaults={
                    "product_category_name": name,
                },
            )
            category_objects[slug] = category

        products = [
            {
                "product_name": "Диван Oslo",
                "product_slug": "divan-oslo",
                "product_category": category_objects["gostinaya"],
                "product_description": "Стильный диван для гостиной с мягкой посадкой.",
                "product_new_price": Decimal("45990.00"),
                "product_old_price": Decimal("51990.00"),
                "product_material": "Велюр",
                "product_color": "Розовый",
                "product_width": Decimal("220.00"),
                "product_height": Decimal("95.00"),
                "product_in_stock": True,
                "product_stock_quantity": 8,
                "product_image": "products/demo_1.jpg",
            },
            {
                "product_name": "Диван Liv",
                "product_slug": "divan-liv",
                "product_category": category_objects["gostinaya"],
                "product_description": "Лаконичный диван с глубоким сиденьем для гостиной или студии.",
                "product_new_price": Decimal("65990.00"),
                "product_old_price": Decimal("72990.00"),
                "product_material": "Букле, массив дерева",
                "product_color": "Молочный",
                "product_width": Decimal("240.00"),
                "product_height": Decimal("88.00"),
                "product_in_stock": True,
                "product_stock_quantity": 5,
                "product_image": "products/demo_2.jpg",
            },
            {
                "product_name": "Кресло Soft",
                "product_slug": "kreslo-soft",
                "product_category": category_objects["gostinaya"],
                "product_description": "Мягкое кресло для зоны отдыха с высокой спинкой.",
                "product_new_price": Decimal("22990.00"),
                "product_old_price": Decimal("26990.00"),
                "product_material": "Велюр, металл",
                "product_color": "Серый",
                "product_width": Decimal("85.00"),
                "product_height": Decimal("95.00"),
                "product_in_stock": True,
                "product_stock_quantity": 10,
                "product_image": "products/demo_3.jpg",
            },
            {
                "product_name": "Журнальный столик Oslo",
                "product_slug": "zhurnalnyy-stolik-oslo",
                "product_category": category_objects["gostinaya"],
                "product_description": "Небольшой журнальный столик с круглой столешницей.",
                "product_new_price": Decimal("12990.00"),
                "product_old_price": Decimal("15990.00"),
                "product_material": "Массив дерева",
                "product_color": "Орех",
                "product_width": Decimal("80.00"),
                "product_height": Decimal("45.00"),
                "product_in_stock": True,
                "product_stock_quantity": 15,
                "product_image": "products/demo_4.jpg",
            },
            {
                "product_name": "ТВ-тумба Line",
                "product_slug": "tv-tumba-line",
                "product_category": category_objects["gostinaya"],
                "product_description": "Низкая тумба под телевизор с закрытыми секциями.",
                "product_new_price": Decimal("19990.00"),
                "product_old_price": Decimal("23990.00"),
                "product_material": "ЛДСП",
                "product_color": "Графит",
                "product_width": Decimal("160.00"),
                "product_height": Decimal("55.00"),
                "product_in_stock": True,
                "product_stock_quantity": 9,
                "product_image": "products/demo_5.jpg",
            },
            {
                "product_name": "Кровать Luna",
                "product_slug": "krovat-luna",
                "product_category": category_objects["spalnya"],
                "product_description": "Кровать с мягким изголовьем.",
                "product_new_price": Decimal("38990.00"),
                "product_old_price": Decimal("42990.00"),
                "product_material": "Дерево",
                "product_color": "Бежевый",
                "product_width": Decimal("180.00"),
                "product_height": Decimal("110.00"),
                "product_in_stock": True,
                "product_stock_quantity": 5,
                "product_image": "products/demo_6.jpg",
            },
            {
                "product_name": "Кровать Aurelia",
                "product_slug": "krovat-aurelia",
                "product_category": category_objects["spalnya"],
                "product_description": "Мягкая кровать с высоким изголовьем и подъёмным механизмом.",
                "product_new_price": Decimal("49990.00"),
                "product_old_price": Decimal("56990.00"),
                "product_material": "Дуб, ткань easy clean",
                "product_color": "Пудровый",
                "product_width": Decimal("160.00"),
                "product_height": Decimal("110.00"),
                "product_in_stock": True,
                "product_stock_quantity": 8,
                "product_image": "products/demo_7.jpg",
            },
            {
                "product_name": "Комод Nordi",
                "product_slug": "komod-nordi",
                "product_category": category_objects["spalnya"],
                "product_description": "Вместительный комод с четырьмя ящиками для спальни.",
                "product_new_price": Decimal("24990.00"),
                "product_old_price": Decimal("29990.00"),
                "product_material": "ЛДСП, МДФ",
                "product_color": "Белый дуб",
                "product_width": Decimal("120.00"),
                "product_height": Decimal("85.00"),
                "product_in_stock": True,
                "product_stock_quantity": 12,
                "product_image": "products/demo_8.jpg",
            },
            {
                "product_name": "Тумба прикроватная Mila",
                "product_slug": "tumba-mila",
                "product_category": category_objects["spalnya"],
                "product_description": "Компактная прикроватная тумба с выдвижным ящиком.",
                "product_new_price": Decimal("8990.00"),
                "product_old_price": Decimal("10990.00"),
                "product_material": "МДФ",
                "product_color": "Бежевый",
                "product_width": Decimal("45.00"),
                "product_height": Decimal("50.00"),
                "product_in_stock": True,
                "product_stock_quantity": 20,
                "product_image": "products/demo_9.jpg",
            },
            {
                "product_name": "Шкаф Vesta",
                "product_slug": "shkaf-vesta",
                "product_category": category_objects["spalnya"],
                "product_description": "Двухдверный шкаф с зеркалом и отделением для одежды.",
                "product_new_price": Decimal("38990.00"),
                "product_old_price": Decimal("44990.00"),
                "product_material": "ЛДСП, зеркало",
                "product_color": "Светлый дуб",
                "product_width": Decimal("180.00"),
                "product_height": Decimal("220.00"),
                "product_in_stock": True,
                "product_stock_quantity": 6,
                "product_image": "products/demo_10.jpg",
            },
            {
                "product_name": "Стол Nordic",
                "product_slug": "stol-nordic",
                "product_category": category_objects["kuhnya"],
                "product_description": "Обеденный стол из массива дерева.",
                "product_new_price": Decimal("19990.00"),
                "product_old_price": Decimal("22990.00"),
                "product_material": "Массив дерева",
                "product_color": "Дуб",
                "product_width": Decimal("140.00"),
                "product_height": Decimal("75.00"),
                "product_in_stock": True,
                "product_stock_quantity": 12,
                "product_image": "products/demo_11.jpg",
            },
            {
                "product_name": "Кухня Mira",
                "product_slug": "kuhnya-mira",
                "product_category": category_objects["kuhnya"],
                "product_description": "Модульная кухня в мягких оттенках с продуманной системой хранения.",
                "product_new_price": Decimal("89990.00"),
                "product_old_price": Decimal("95990.00"),
                "product_material": "МДФ, ЛДСП",
                "product_color": "Оливковый",
                "product_width": Decimal("320.00"),
                "product_height": Decimal("240.00"),
                "product_in_stock": True,
                "product_stock_quantity": 4,
                "product_image": "products/demo_12.jpg",
            },
            {
                "product_name": "Обеденный стол Terra",
                "product_slug": "obedennyy-stol-terra",
                "product_category": category_objects["kuhnya"],
                "product_description": "Прочный обеденный стол для кухни или столовой.",
                "product_new_price": Decimal("27990.00"),
                "product_old_price": Decimal("32990.00"),
                "product_material": "Массив ясеня",
                "product_color": "Натуральный",
                "product_width": Decimal("160.00"),
                "product_height": Decimal("76.00"),
                "product_in_stock": True,
                "product_stock_quantity": 7,
                "product_image": "products/demo_13.jpg",
            },
            {
                "product_name": "Стул Verona",
                "product_slug": "stul-verona",
                "product_category": category_objects["kuhnya"],
                "product_description": "Удобный кухонный стул с мягким сиденьем.",
                "product_new_price": Decimal("6990.00"),
                "product_old_price": Decimal("8490.00"),
                "product_material": "Металл, ткань",
                "product_color": "Бежевый",
                "product_width": Decimal("45.00"),
                "product_height": Decimal("88.00"),
                "product_in_stock": True,
                "product_stock_quantity": 30,
                "product_image": "products/demo_14.jpg",
            },
            {
                "product_name": "Кухонный остров Prime",
                "product_slug": "kuhonnyy-ostrov-prime",
                "product_category": category_objects["kuhnya"],
                "product_description": "Функциональный кухонный остров с дополнительными полками.",
                "product_new_price": Decimal("45990.00"),
                "product_old_price": Decimal("51990.00"),
                "product_material": "МДФ, каменная столешница",
                "product_color": "Белый",
                "product_width": Decimal("140.00"),
                "product_height": Decimal("90.00"),
                "product_in_stock": True,
                "product_stock_quantity": 3,
                "product_image": "products/demo_15.jpg",
            },
            {
                "product_name": "Прихожая Vela",
                "product_slug": "prihozhaya-vela",
                "product_category": category_objects["prihozhaya"],
                "product_description": "Комплект для прихожей с мягкой банкеткой и вместительным шкафом.",
                "product_new_price": Decimal("34990.00"),
                "product_old_price": Decimal("39990.00"),
                "product_material": "Шпон, ткань",
                "product_color": "Песочный",
                "product_width": Decimal("180.00"),
                "product_height": Decimal("210.00"),
                "product_in_stock": True,
                "product_stock_quantity": 6,
                "product_image": "products/demo_16.jpg",
            },
            {
                "product_name": "Обувница Compact",
                "product_slug": "obuvnica-compact",
                "product_category": category_objects["prihozhaya"],
                "product_description": "Узкая обувница для небольшой прихожей.",
                "product_new_price": Decimal("11990.00"),
                "product_old_price": Decimal("13990.00"),
                "product_material": "ЛДСП",
                "product_color": "Белый",
                "product_width": Decimal("80.00"),
                "product_height": Decimal("105.00"),
                "product_in_stock": True,
                "product_stock_quantity": 18,
                "product_image": "products/demo_17.jpg",
            },
            {
                "product_name": "Вешалка Loft",
                "product_slug": "veshalka-loft",
                "product_category": category_objects["prihozhaya"],
                "product_description": "Настенная вешалка с полкой для головных уборов.",
                "product_new_price": Decimal("7990.00"),
                "product_old_price": Decimal("9990.00"),
                "product_material": "Металл, дерево",
                "product_color": "Чёрный",
                "product_width": Decimal("100.00"),
                "product_height": Decimal("35.00"),
                "product_in_stock": True,
                "product_stock_quantity": 22,
                "product_image": "products/demo_18.jpg",
            },
            {
                "product_name": "Тумба Luna",
                "product_slug": "tumba-luna",
                "product_category": category_objects["vannaya"],
                "product_description": "Подвесная тумба с круглым зеркалом для современной ванной комнаты.",
                "product_new_price": Decimal("28990.00"),
                "product_old_price": Decimal("32990.00"),
                "product_material": "Влагостойкий МДФ",
                "product_color": "Розовый кварц",
                "product_width": Decimal("90.00"),
                "product_height": Decimal("60.00"),
                "product_in_stock": True,
                "product_stock_quantity": 8,
                "product_image": "products/demo_19.jpg",
            },
            {
                "product_name": "Зеркало Aura",
                "product_slug": "zerkalo-aura",
                "product_category": category_objects["vannaya"],
                "product_description": "Круглое зеркало с LED-подсветкой.",
                "product_new_price": Decimal("14990.00"),
                "product_old_price": Decimal("17990.00"),
                "product_material": "Зеркальное стекло, металл",
                "product_color": "Серебристый",
                "product_width": Decimal("80.00"),
                "product_height": Decimal("80.00"),
                "product_in_stock": True,
                "product_stock_quantity": 14,
                "product_image": "products/demo_20.jpg",
            },
            {
                "product_name": "Пенал Aqua",
                "product_slug": "penal-aqua",
                "product_category": category_objects["vannaya"],
                "product_description": "Узкий пенал для хранения полотенец и бытовых средств.",
                "product_new_price": Decimal("21990.00"),
                "product_old_price": Decimal("24990.00"),
                "product_material": "Влагостойкий ЛДСП",
                "product_color": "Белый",
                "product_width": Decimal("40.00"),
                "product_height": Decimal("190.00"),
                "product_in_stock": True,
                "product_stock_quantity": 9,
                "product_image": "products/demo_21.jpg",
            },
            {
                "product_name": "Стол Nord",
                "product_slug": "stol-nord",
                "product_category": category_objects["kabinet"],
                "product_description": "Рабочий стол со скрытым отсеком для проводов.",
                "product_new_price": Decimal("21990.00"),
                "product_old_price": Decimal("25990.00"),
                "product_material": "Дуб, металл",
                "product_color": "Натуральный",
                "product_width": Decimal("140.00"),
                "product_height": Decimal("75.00"),
                "product_in_stock": True,
                "product_stock_quantity": 11,
                "product_image": "products/demo_22.jpg",
            },
            {
                "product_name": "Кресло Manager",
                "product_slug": "kreslo-manager",
                "product_category": category_objects["kabinet"],
                "product_description": "Офисное кресло с регулировкой высоты и наклона.",
                "product_new_price": Decimal("18990.00"),
                "product_old_price": Decimal("22990.00"),
                "product_material": "Экокожа, металл",
                "product_color": "Чёрный",
                "product_width": Decimal("65.00"),
                "product_height": Decimal("120.00"),
                "product_in_stock": True,
                "product_stock_quantity": 16,
                "product_image": "products/demo_23.jpg",
            },
            {
                "product_name": "Стеллаж Bookline",
                "product_slug": "stellazh-bookline",
                "product_category": category_objects["kabinet"],
                "product_description": "Высокий стеллаж для книг, декора и документов.",
                "product_new_price": Decimal("17990.00"),
                "product_old_price": Decimal("20990.00"),
                "product_material": "ЛДСП",
                "product_color": "Орех",
                "product_width": Decimal("90.00"),
                "product_height": Decimal("200.00"),
                "product_in_stock": True,
                "product_stock_quantity": 13,
                "product_image": "products/demo_24.jpg",
            },
            {
                "product_name": "Кровать детская Cloud",
                "product_slug": "krovat-detskaya-cloud",
                "product_category": category_objects["detskaya"],
                "product_description": "Детская кровать с бортиками и безопасными скруглёнными углами.",
                "product_new_price": Decimal("26990.00"),
                "product_old_price": Decimal("30990.00"),
                "product_material": "Массив сосны",
                "product_color": "Белый",
                "product_width": Decimal("90.00"),
                "product_height": Decimal("80.00"),
                "product_in_stock": True,
                "product_stock_quantity": 9,
                "product_image": "products/demo_25.jpg",
            },
            {
                "product_name": "Письменный стол Junior",
                "product_slug": "pismennyy-stol-junior",
                "product_category": category_objects["detskaya"],
                "product_description": "Письменный стол для школьника с ящиками для хранения.",
                "product_new_price": Decimal("16990.00"),
                "product_old_price": Decimal("19990.00"),
                "product_material": "ЛДСП",
                "product_color": "Светлый дуб",
                "product_width": Decimal("120.00"),
                "product_height": Decimal("75.00"),
                "product_in_stock": True,
                "product_stock_quantity": 12,
                "product_image": "products/demo_26.jpg",
            },
            {
                "product_name": "Шкаф Teddy",
                "product_slug": "shkaf-teddy",
                "product_category": category_objects["detskaya"],
                "product_description": "Детский шкаф для одежды с полками и штангой.",
                "product_new_price": Decimal("29990.00"),
                "product_old_price": Decimal("34990.00"),
                "product_material": "МДФ, ЛДСП",
                "product_color": "Мятный",
                "product_width": Decimal("120.00"),
                "product_height": Decimal("190.00"),
                "product_in_stock": True,
                "product_stock_quantity": 7,
                "product_image": "products/demo_27.jpg",
            }
            ]
        created_products = []

        for data in products:
            product, _ = Product.objects.update_or_create(
                product_slug=data["product_slug"],
                defaults=data,
            )
            created_products.append(product)

        for index, product in enumerate(created_products, start=1):
            ProductImage.objects.get_or_create(
                product=product,
                product_order=1,
                defaults={
                    "product_image": f"products/demo_{index}.jpg",
                    "product_alt": product.product_name,
                },
            )

        cart, _ = Cart.objects.get_or_create(user=user)

        for product in created_products[:2]:
            CartItem.objects.get_or_create(
                cart=cart,
                product=product,
                defaults={
                    "quantity": 1,
                },
            )

        order_total = sum(product.product_new_price for product in created_products[:2])

        order, _ = Order.objects.get_or_create(
            order_num="ORD-DEMO-001",
            defaults={
                "user": user,
                "order_status": "new",
                "order_total_sum": order_total,
                "order_delivery_address": "Москва, ул. Центральная, д. 15",
                "order_payment_method": "card",
            },
        )

        for product in created_products[:2]:
            OrderItem.objects.get_or_create(
                order=order,
                product=product,
                defaults={
                    "product_price": product.product_new_price,
                    "order_item_quantity": 1,
                    "order_item_total_sum": product.product_new_price,
                },
            )

        self.stdout.write(self.style.SUCCESS("База данных успешно заполнена одной командой."))
